import { Router } from "express";
import userRoutes from "../admin/auth/user.route";
import roleRoutes from "../admin/role/role.route";
import configurationRotes from "../admin/configuration/configuration.route";
import eventRoutes from "../ddg/events/events.route";
import departmentRoutes from "../ddg/departments/department.route";
import attendanceStatusRoutes from "../ddg/attendance/attendance_status/attendance_status.route";
import assignamentRoutes from "../admin/assignaments/assignament.route";
import dashboardRoutes from "../ddg/dashboard/dashboard.route";
import attendanceRoute from "../ddg/attendance/users_attendance/users_attendance.route";
import productCategorieRoure from "../coffe/product_categories/product_categorie.route";
import productRoutes from "../coffe/products/products.route";
import menuRoutes from "../coffe/menus/menus.route";
import menuSectionRoutes from "../coffe/menu_sections/menu_sections.route";
import menuItemRoutes from "../coffe/menu_items/menu_items.route";
import saleRoutes from "../coffe/sales/sales.route";
import saleLineRoutes from "../coffe/sale_lines/sale_lines.route";
import userCardRoutes from "../ddg/user_cards/user_card.route";

const router = Router();

router.use("/admin/auth", userRoutes);
router.use("/admin/role", roleRoutes);
router.use("/admin/assignament", assignamentRoutes);
router.use("/admin/configuration", configurationRotes);
router.use("/ddg/events", eventRoutes);
router.use("/ddg/departments", departmentRoutes);
router.use("/ddg/attendance-status", attendanceStatusRoutes);
router.use("/ddg/dashboard", dashboardRoutes);
router.use("/ddg/attendance", attendanceRoute);
router.use("/ddg/user-cards", userCardRoutes);
router.use("/coffee/product-categories", productCategorieRoure);
router.use("/coffee/products", productRoutes);
router.use("/coffee/menus", menuRoutes);
router.use("/coffee/menu-sections", menuSectionRoutes);
router.use("/coffee/menu-items", menuItemRoutes);
router.use("/coffee/sales", saleRoutes);
router.use("/coffee/sale-lines", saleLineRoutes);

export default router;
